### ISSUE TITLE
JWT필터 스치기만 해도 터지는 문제는

### ISSUE THREAD

**Issue by potados99** [idorm/idorm-server#11]
https://github.com/idorm/idorm-server/blob/80b56379d85c85154d7f230fd37a654c707bf12c/src/main/java/idorm/idormServer/auth/JwtAuthenticationFilter.java#L27

죠기 저 유저네임 가져오는 부분이 토큰이 null일 때에도 실행되어서 그런 것 같으니, 해당 코드를 31줄에서 열리는 if 블럭 안쪽으로 이동시키면 토큰이 null이 아닐 때에만 실행되어 괜찮을 것 같읍니다 ㅎ

홧팅!!

**Comment by nahyeon99** [comment]
덕분에 해결했읍니다,, 늘 감쟈해요,, 껄껄
